# configure our cumulus linux host as a switch
---
- hosts: all
  become: yes

  tasks:
    - name: wait until ssh is reachable
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: install apt packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - tcpdump

# network configuration
    - name: copy network interfaces
      copy:
        src: iface.cfg
        dest: /etc/network/interfaces

    - name: bring up eth1
      shell: ip addr del 10.0.0.1/24 dev eth1
      ignore_errors: yes

    - name: bring up eth1
      shell: ip addr add 10.0.0.1/24 dev eth1

    - name: take down eth1
      shell: ip link set eth1 down
      ignore_errors: yes

    - name: bring up eth1
      shell: ip link set eth1 up

# pxeboot-store container

    - name: install docker
      script: get-docker.sh

    - name: copy pxeboot config
      copy:
        src: pxeboot.service
        dest: /etc/systemd/system/pxeboot.service

    - name: start container
      systemd:
        state: started
        enabled: True
        name: pxeboot

# nex deployment
    - name: make nex directory
      file:
        path: /etc/nex/
        state: directory

    - name: copy pxeboot config
      copy:
        src: nex.cfg
        dest: /etc/nex/sled.yml
